### ISSUE TITLE
Erroneous createMany type

### ISSUE THREAD

**Issue by matthieuMay** [teamMay/factory#144]
This code raises a typescript error while it is correctly interpretated. We should accept sequence as a possible input for createMany

```typescript
await eventsFactory.createMany(10, {
      discussion: discussion2,
      createdAt: new Sequence((nb: number) => new Date(now - nb * 10000)),
    })
```

**Comment by adrien-may** [comment]
So far, we expected all inner utils (Sequence, LazyAttributes and so on...) to be used only within factories definition (within `attrs`). Not in the `create`, `createMany`, `build` (...) methods.

That being said, if it works as is and only a typing evolution is required... Have a look at PR #147 and tell me if that's working for you.
