### ISSUE TITLE
adapters, monorepo and deps

### ISSUE THREAD

**Issue by adrien-may** [teamMay/factory#2]
So far, typeorm is a dependency of this package and no other adapter is provided.
This won't be a good solution for long if we want new adapters and avoid useless dependencies.

We may decide to remove the typeorm part to a new repo or use a monorepo here and add adapters + dedicated factory's SubClass in different sections.

Right now, we need to try this library a bit before deciding to expand it to other use.

**Comment by jorgebodega** [comment]
Hi! I've been reading and I find this library quite interesting. I could bring here everything related with github actions to help on deploys and check if I can take something from my library to include it.

**Comment by adrien-may** [comment]
Hi! Happy to know you like it. I create Issue #3 for github actions / deploys. I'll let this issue open on the adapters/monorepo subject. I'm open to suggestions and any help is very welcomed.
