### ISSUE TITLE
TypeScript support on `attrs` +  show example of 1:N "SubFactory" 

### ISSUE THREAD

**Issue by kevin-mitchell** [teamMay/factory#5]
The readme mentions one to many relationships, but as far as I can tell the docs don't describe how this would be done. 

In all situation's it seems that TS is unhappy with a `Promise<MyType[]>` - the promise being the issue.

It would be useful to have examples of One-to-Many, as well as Many-to-Many, and Many-to-One (the inverse).

**Comment by adrien-may** [comment]
To have more examples, you can have a look in the test folder. There are many example with different kind of relationships.

Indeed, typescript expect instances of your entities and not promises. This lib "await" for your results before assignation. What it means:

for OneToOne or ManyToOne, you can use:

```typescript
attrs ={
  // ...
  myType: new SubFactory(MyTypeFactory) 
}
```

In case of ManyToMany, it usually means entities can be created with an empty m2m and be populated afterwards.
I would tend to use a `PostGeneration` for this particular case. Also, it can be more difficult to handle factories "a bit too smart" which creates a lot of relationships.

I would use something like this:

```typescript
class ParentFactory extends Factory<Parent> {
  // ....
  @PostGeneration()
  async addingChildren(instance: Parent) {
    instance.children = await new ChildFactory().createMany(2);
    // depending on your model definition, you could need to write
    // instance.children = await new ChildFactory().createMany(2, { parent: instance });  
  }
```

Another approach would be *outside* of factories definition directly without any postGeneration

```typescript
const parent = await new ParentFactory().create();
const children = await new MyTypeFactory().createMany(2, { parent });
```

I hope it answers your question. I'd be very grateful to review a PR from you adding more documentation if you find it that misleading.

**Comment by kevin-mitchell** [comment]
Thanks again for the reply :).

Before I posted I did spend some time looking at your tests, but I ran into issues there as well. _I apologize in advance if this is just an issue with my local setup_, but my process was 

1. clone this repo
2. run `npm install`
3. make the changes I mention below

After doing that, I opened up https://github.com/teamMay/factory/blob/fea4bbfab691fe989a4df9d46fb3c075809503cf/__tests__/factories/cook.factory.ts and see 

> `'attrs' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.ts`

_I am beginning to suspect my local setup is the issue here_, but I'm still wondering if this could be an issue you've seen?

<img width="948" alt="Screen Shot 2022-02-04 at 8 50 31 AM" src="https://user-images.githubusercontent.com/21270844/152540215-2822c7ab-71e1-4c61-9457-9d995ca94d1d.png">


If I explicitly set the type (I'm now switching to your `Restaurant` factory test) with what I think is the correct type, `ConstructableAttrs<Restaurant>`, and attempt to use the `SubFactory` for the `cooks`:

```typescript
  attrs: ConstructableAttrs<Restaurant> = {
    name: 'Beau gosse Kebab',
    open: true,
    description: 'Best kebab in Caen',
    cooks: new SubFactory(CookFactory),
  };
```

Then I see `Type 'Cook' is not assignable to type 'Cook[]'` - I realize this makes sense, because indeed the Cook factory only generates a single Cook, but I'm wondering if there is a solution for this? In other words, can I tell the `SubFactory` to generate an array of items?

 I see in your example you use the `@PostGeneration()` to add the cooks to the restaurant afterwards. That works for me I think, so I'll try to go that route for now.

Sorry, lots of words, just trying to figure out the best way to use the library :).

**Comment by adrien-may** [comment]
I figure it out.

Your problem is:

when defining your "email", you need to use a LazyAttribute so that you can access the result of your value.

Using 

```typescript
 mail: new LazyAttribute((instance: Cook) => `${instance.firstName}@email-fake.com`),
```
 would work.

About the second example, for manyToMany it may be more interesting to use a PostGeneration hook as you mentionned or use the code i wrote in my first comment on this issue.

**Comment by kevin-mitchell** [comment]
FYI, my examples are from your example tests: https://github.com/teamMay/factory/blob/develop/__tests__/factories/cook.factory.ts

Sorry, make this was clear, but I just wanted to make sure you knew I was using your repo / tests, not my own.

**Comment by adrien-may** [comment]
About the `attrs` "problem", maybe check the tsconfig file provided with the project. Maybe your IDE isn't using it ? I don't have any errors on my side but I may be missing something. I'm not aware of it if I do have a setup problem...

I thought you were changing the examples, my bad. (I wasn't checking the good cook.factory file)
